name: ci

on:
  push:
    branches: [main]
  pull_request:

jobs:
  python-security:
    uses: project-unisonOS/.github/.github/workflows/reusable-python-security.yml@464c814924465fd1a7dc06d3fea29daae5762a11
    with:
      python-version: "3.12"
      working-directory: "."
      unison-common-ref: "7d8ac82fd5605dba2791c9ed34148c69f40897cc"
      enable-principal-binding-test-bypass: true

  container-supply-chain:
    uses: project-unisonOS/.github/.github/workflows/reusable-container-supply-chain.yml@464c814924465fd1a7dc06d3fea29daae5762a11
    with:
      image-name: unison-orchestrator
      dockerfile: Dockerfile
      context: .
