name: ci

on:
  push:
    branches: [main]
  pull_request:

jobs:
  python-security:
    uses: project-unisonOS/.github/.github/workflows/reusable-python-security.yml@7b392529550f2963dc0022428e873ddb17cdedd4
    with:
      python-version: "3.12"
      working-directory: "."
      unison-common-ref: "04fed97fae46959485e7fc52d6d9e06c7d8262aa"
      enable-principal-binding-test-bypass: true

  container-supply-chain:
    uses: project-unisonOS/.github/.github/workflows/reusable-container-supply-chain.yml@7b392529550f2963dc0022428e873ddb17cdedd4
    with:
      image-name: unison-orchestrator
      dockerfile: Dockerfile
      context: .
